<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>LORAP</AssemblyName>
    <Description>Bruh</Description>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
	<RestoreAdditionalProjectSources>
	  https://api.nuget.org/v3/index.json;
	  https://nuget.bepinex.dev/v3/index.json;
	  https://nuget.samboy.dev/v3/index.json
	</RestoreAdditionalProjectSources>
	<Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.5.0" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.3.5" />
	<PackageReference Include="UnityEngine.Modules" Version="2019.3.15" IncludeAssets="compile" />
	
	<Publicize Include="Assembly-CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Library Of Ruina\LibraryOfRuina_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Library Of Ruina\LibraryOfRuina_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Library Of Ruina\LibraryOfRuina_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Runtime.Serialization">
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Numerics">
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System">
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>